### ISSUE TITLE
Sway instance doesn't launch on X11 environment under Mate

### ISSUE THREAD

**Issue by rea987** [Tau5/Co-op-on-Linux#3]
Sway instance doesn't launch on X11 environment under Mate. I rebooted the system to try sway window manager, it started but with an empty window with no tool or window manager. It looks like sway is looking for xwayland rather than x11.

https://gist.github.com/rea987/10b6198cf64a8c5e2ef9c250b6c1f3e5

Used release; v0.3.

**Comment by Tau5** [comment]
I think that if you only see an empty window then it is working, just that it's misconfigured because of the previous issue with the controller selector. I've now added a check to see if the controller selector opened correctly before trying to open sway.

I've tried to replicate the issue but I couldn't so I think this could be the reason

I may add Xwayland as a dependency as any game will require it to run, but you can still use MATE and use Xwayland, because it will be the sway session that uses it

**Comment by rea987** [comment]
> I think that if you only see an empty window then it is working, just that it's misconfigured because of the previous issue with the controller selector.

The controllers are now configured but the tool is still giving empty window. I switched from Wine via Lutris (NSFMW) to native (Dungeon Defenders [DRM-Free]); the result is still the same.

https://gist.github.com/rea987/807b03f0bc9a921fad7eba89f5f4fc13

Seeing that the errors related with xwayland, I highly suspect that sway and/or the tool is looking for Xwayland and/or Wayland rather than utilizing existing X11.

**Comment by Tau5** [comment]
Could you install `xwayland` with apt and try again?

**Comment by rea987** [comment]
Unfortunately I lack time to test it properly. Let me temporarily close the issue until I find time to reopen.
